theme: jekyll-theme-minimal
title: Hà Minh Quân (DuckMofii) 
description: Explore the portfolio of Hà Minh Quân (DuckMofii), an AI Engineer focusing on Chatbots, LLMs, NLP, and AI Agents development. Let's build the future of intelligent interaction.